"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "assets/translations/en-US/main.ftl",
    "translation": "assets/translations/%locale%/%original_file_name%"
  }
]