# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY

# Regular strings
key_s = ['s]['s]
About = [Àbóút][Àbóút]
Add = [Àdd][Àdd]
Add_Wallet = [Àdd Wàllét]
Add_a_different_wallet_that_will_only_be_used_for_this_account = [Àdd à dífféréñt wàllét thàt wíll óñly bé úséd fór thís àççóúñt]
Add_a_wallet_to_continue = [Àdd à wàllét tó çóñtíñúé]
Add_relay = [Àdd rélày]
Banner = [Bàññér][Bàññér]
# Broadcast the note to all connected relays
Broadcast = [Bróàdçàst]
# Broadcast the note only to local network relays
Broadcast_Local = [Bróàdçàst Lóçàl]
Cancel = [Çàñçél][Çàñçél]
Click_to_edit = [Çlíçk tó édít]
Confirm = [Çóñfírm][Çóñfírm]
Copy = [Çópy][Çópy]
Copy_Link = [Çópy Líñk]
# Copy the unique note identifier to clipboard
Copy_Note_ID = [Çópy Ñóté ÍD]
# Copy the raw note data in JSON format to clipboard
Copy_Note_JSON = [Çópy Ñóté JSÓÑ]
# Copy the author's public key to clipboard
Copy_Pubkey = [Çópy Púbkéy]
# Copy the text content of the note to clipboard
Copy_Text = [Çópy Téxt]
Deck_name = [Déçk ñàmé]
Default_amount_per_zap_ = [Défàúlt àmóúñt pér zàp:]
Delete_Wallet = [Délété Wàllét]
Delete_this_column = [Délété thís çólúmñ]
Display_name = [Dísplày ñàmé]
ERROR__Could_not_find_logs_on_system = [ÉRRÓR: Çóúld ñót fíñd lógs óñ systém]
Enter_the_relay_here = [Éñtér thé rélày héré]
Icon = [Íçóñ][Íçóñ]
Invalid_NWC_URI = [Íñvàlíd ÑWÇ ÚRÍ]
Invalid_amount = [Íñvàlíd àmóúñt]
Lightning_network_address__lud16 = [Líghtñíñg ñétwórk àddréss (lúd16]
Media_from_someone_you_don_t_follow = [Médíà fróm sóméóñé yóú dóñ't fóllów]
Moves_this_column_to_another_position = [Móvés thís çólúmñ tó àñóthér pósítíóñ]
Nostr_address__NIP-05_identity = [Ñóstr àddréss (ÑÍP-05 ídéñtíty]
Open_Email = [Ópéñ Émàíl]
Open_your_default_email_client_to_get_help_from_the_Damus_team = [Ópéñ yóúr défàúlt émàíl çlíéñt tó gét hélp fróm thé Dàmús téàm]
Press_the_button_below_to_copy_your_most_recent_logs_to_your_system_s_clipboard__Then_paste_it_into_your_email_ = [Préss thé búttóñ bélów tó çópy yóúr móst réçéñt lógs tó yóúr systém's çlípbóàrd. Théñ pàsté ít íñtó yóúr émàíl.]
Profile_picture = [Prófílé píçtúré]
Quote_of_unknown_note = [Qúóté óf úñkñówñ ñóté]
Relays = [Rélàys][Rélàys]
Reply_to_unknown_note = [Réply tó úñkñówñ ñóté]
Running_into_a_bug_ = [Rúññíñg íñtó à búg?]
Save = [Sàvé][Sàvé]
Save_changes = [Sàvé çhàñgés]
Step_1 = [Stép 1][Stép 1]
Step_2 = [Stép 2][Stép 2]
Tap_to_Load = [Tàp tó Lóàd]
Use_this_wallet_for_the_current_account_only = [Úsé thís wàllét fór thé çúrréñt àççóúñt óñly]
Username = [Úsérñàmé]
We_recommend_short_names = [Wé réçómméñd shórt ñàmés]
Website = [Wébsíté][Wébsíté]
a_note = [à ñóté][à ñóté]
create_a_name_for_the_deck = [çréàté à ñàmé fór thé déçk]
in = [íñ][íñ]
in_someone_s_thread = [íñ sóméóñé's thréàd]
note = [ñóté][ñóté]
paste = [pàsté][pàsté]
replying_to = [réplyíñg tó]
sats = [sàts][sàts]
select_an_icon = [séléçt àñ íçóñ]
thread = [thréàd][thréàd]

# Context-specific translations
# Error loading thread: {error:?} used as error
Error_loading_thread___error____error = [Érrór lóàdíñg thréàd: {érrór:?}]

# Please {message}. used as message
Please__message___message = [Pléàsé {méssàgé}.]

# error: could not find {list_kind:?} used as list_kind
error__could_not_find__list_kind____list_kind = [érrór: çóúld ñót fíñd {líst_kíñd:?}]
