# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY

# Regular strings
# Broadcast the note to all connected relays
Broadcast = Broadcast
# Broadcast the note only to local network relays
Broadcast Local = Broadcast Local
# Copy the unique note identifier to clipboard
Copy Note ID = Copy Note ID
# Copy the raw note data in JSON format to clipboard
Copy Note JSON = Copy Note JSON
# Copy the text content of the note to clipboard
Copy Text = Copy Text
