# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY

# Regular strings
 Add relay =  Add relay
 sats =  sats
About = About
Add = Add
Add Wallet = Add Wallet
Add a different wallet that will only be used for this account = Add a different wallet that will only be used for this account
Add a wallet to continue = Add a wallet to continue
Banner = Banner
# Broadcast the note to all connected relays
Broadcast = Broadcast
# Broadcast the note only to local network relays
Broadcast Local = Broadcast Local
Cancel = Cancel
Click to edit = Click to edit
Confirm = Confirm
Copy = Copy
Copy Link = Copy Link
# Copy the unique note identifier to clipboard
Copy Note ID = Copy Note ID
# Copy the raw note data in JSON format to clipboard
Copy Note JSON = Copy Note JSON
# Copy the text content of the note to clipboard
Copy Text = Copy Text
Default amount per zap:  = Default amount per zap: 
Delete Wallet = Delete Wallet
Delete this column = Delete this column
Display name = Display name
ERROR: Could not find logs on system = ERROR: Could not find logs on system
Enter the relay here = Enter the relay here
Invalid NWC URI = Invalid NWC URI
Invalid amount = Invalid amount
Lightning network address (lud16) = Lightning network address (lud16)
Moves this column to another position = Moves this column to another position
Nostr address (NIP-05 identity) = Nostr address (NIP-05 identity)
Open Email = Open Email
Open your default email client to get help from the Damus team = Open your default email client to get help from the Damus team
Profile picture = Profile picture
Quote of unknown note = Quote of unknown note
Relays = Relays
Reply to unknown note = Reply to unknown note
Running into a bug? = Running into a bug?
Save = Save
Save changes = Save changes
Step 1 = Step 1
Step 2 = Step 2
Tap to Load = Tap to Load
Use this wallet for the current account only = Use this wallet for the current account only
Username = Username
Website = Website
a note = a note
in = in
note = note
paste = paste
replying to = replying to
thread = thread
