#!/usr/bin/env python3
"""
Extract i18n macros from Rust code and generate main.ftl file.

This script scans all Rust files in the project for tr! and tr_with_context! macro calls
and generates a main.ftl file with all the extracted strings.
"""

import os
import re
import argparse
from pathlib import Path
from typing import Set, Dict, List, Tuple
import json

def find_rust_files(project_root: Path) -> List[Path]:
    """Find all Rust files in the project."""
    rust_files = []
    for root, dirs, files in os.walk(project_root):
        # Skip target and .git directories
        dirs[:] = [d for d in dirs if d not in ['target', '.git', 'node_modules']]
        
        for file in files:
            if file.endswith('.rs'):
                rust_files.append(Path(root) / file)
    
    return rust_files

def extract_tr_macros(content: str) -> Dict[str, str]:
    """Extract tr! macro calls from Rust code with optional comments."""
    # Pattern for tr!("string") or tr!("string", "comment")
    tr_pattern = r'tr!\s*\(\s*["\']([^"\']{1,100})["\'](?:\s*,\s*["\']([^"\']{1,200})["\'])?\s*\)'
    matches = re.findall(tr_pattern, content)
    
    # Filter out obvious false positives and collect with comments
    filtered_matches = {}
    for match in matches:
        key = match[0]
        comment = match[1] if len(match) > 1 and match[1] else ""
        
        # Skip file paths, URLs, and other non-UI strings
        if not any(skip in key.lower() for skip in [
            '/', '\\', '.ftl', '.rs', 'http', 'https', 'www', '@', 
            'crates/', 'src/', 'target/', 'build.rs'
        ]):
            filtered_matches[key] = comment
    
    return filtered_matches

def extract_tr_with_context_macros(content: str) -> Dict[Tuple[str, str], str]:
    """Extract tr_with_context! macro calls from Rust code with optional comments."""
    # Pattern for tr_with_context!("string", "context") or tr_with_context!("string", "context", "comment")
    tr_context_pattern = r'tr_with_context!\s*\(\s*["\']([^"\']{1,100})["\']\s*,\s*["\']([^"\']{1,50})["\'](?:\s*,\s*["\']([^"\']{1,200})["\'])?\s*\)'
    matches = re.findall(tr_context_pattern, content)
    
    # Filter out obvious false positives and collect with comments
    filtered_matches = {}
    for match in matches:
        base = match[0]
        context = match[1]
        comment = match[2] if len(match) > 2 and match[2] else ""
        
        if not any(skip in base.lower() for skip in [
            '/', '\\', '.ftl', '.rs', 'http', 'https', 'www', '@',
            'crates/', 'src/', 'target/', 'build.rs'
        ]):
            filtered_matches[(base, context)] = comment
    
    return filtered_matches

def extract_tr_plural_macros(content: str) -> Dict[str, str]:
    """Extract tr_plural! macro calls from Rust code with optional comments."""
    # Pattern for tr_plural!("string", count) or tr_plural!("string", count, "comment")
    tr_plural_pattern = r'tr_plural!\s*\(\s*["\']([^"\']{1,100})["\']\s*,(?:\s*["\']([^"\']{1,200})["\']\s*,)?'
    matches = re.findall(tr_plural_pattern, content)
    
    # Filter out obvious false positives and collect with comments
    filtered_matches = {}
    for match in matches:
        key = match[0]
        comment = match[1] if len(match) > 1 and match[1] else ""
        
        if not any(skip in key.lower() for skip in [
            '/', '\\', '.ftl', '.rs', 'http', 'https', 'www', '@',
            'crates/', 'src/', 'target/', 'build.rs'
        ]):
            filtered_matches[key] = comment
    
    return filtered_matches

def generate_ftl_content(tr_strings: Dict[str, str], 
                        context_strings: Dict[Tuple[str, str], str], 
                        plural_strings: Dict[str, str]) -> str:
    """Generate FTL file content from extracted strings with comments."""
    
    lines = [
        "# Main translation file for Notedeck",
        "# This file contains common UI strings used throughout the application",
        "# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY",
        "",
    ]
    
    # Sort strings for consistent output
    sorted_tr = sorted(tr_strings.items())
    sorted_context = sorted(context_strings.items())
    sorted_plural = sorted(plural_strings.items())
    
    # Add regular tr! strings
    if sorted_tr:
        lines.append("# Regular strings")
        for string, comment in sorted_tr:
            # Skip if it's a context string (will be handled separately)
            if not any(string == base and context for (base, context), _ in context_strings.items()):
                if comment:
                    lines.append(f"# {comment}")
                lines.append(f"{string} = {string}")
        lines.append("")
    
    # Add context-aware strings
    if sorted_context:
        lines.append("# Context-specific translations")
        current_base = None
        for (base, context), comment in sorted_context:
            if base != current_base:
                if current_base is not None:
                    lines.append("")
                current_base = base
                if comment:
                    lines.append(f"# {comment}")
                else:
                    lines.append(f"# {base} used as {context}")
            lines.append(f"{base}#{context} = {base}")
        lines.append("")
    
    # Add pluralized strings
    if sorted_plural:
        lines.append("# Pluralized strings")
        for string, comment in sorted_plural:
            # Generate basic pluralization pattern
            if "$count" in string:
                # Extract the base form (e.g., "minutes ago" from "$count minutes ago")
                base_form = string.replace("$count ", "")
                singular_form = base_form.replace("s ", " ", 1) if base_form.startswith("s ") else base_form
                
                if comment:
                    lines.append(f"# {comment}")
                else:
                    lines.append(f"# {string} with pluralization")
                lines.append(f'{string} = {{ $count ->')
                lines.append(f'    [1] 1 {singular_form}')
                lines.append(f'    *[other] {{ $count }} {base_form}')
                lines.append(f'}}')
                lines.append("")
    
    return "\n".join(lines)

def read_existing_ftl(ftl_path: Path) -> Dict[str, str]:
    """Read existing FTL file to preserve comments and custom translations."""
    if not ftl_path.exists():
        return {}
    
    existing_translations = {}
    with open(ftl_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract key-value pairs
    pattern = r'^([^#\s][^=]*?)\s*=\s*(.+)$'
    for line in content.split('\n'):
        match = re.match(pattern, line.strip())
        if match:
            key = match.group(1).strip()
            value = match.group(2).strip()
            existing_translations[key] = value
    
    return existing_translations

def main():
    parser = argparse.ArgumentParser(description='Extract i18n macros and generate FTL file')
    parser.add_argument('--project-root', type=str, default='.', 
                       help='Project root directory (default: current directory)')
    parser.add_argument('--output', type=str, 
                       default='crates/notedeck/src/i18n/locales/en-US/main.ftl',
                       help='Output FTL file path')
    parser.add_argument('--dry-run', action='store_true',
                       help='Show what would be generated without writing to file')
    
    args = parser.parse_args()
    
    project_root = Path(args.project_root)
    output_path = Path(args.output)
    
    print(f"Scanning Rust files in {project_root}...")
    
    # Find all Rust files
    rust_files = find_rust_files(project_root)
    print(f"Found {len(rust_files)} Rust files")
    
    # Extract strings from all files
    all_tr_strings = {}
    all_context_strings = {}
    all_plural_strings = {}
    
    for rust_file in rust_files:
        try:
            with open(rust_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            tr_strings = extract_tr_macros(content)
            context_strings = extract_tr_with_context_macros(content)
            plural_strings = extract_tr_plural_macros(content)
            
            if tr_strings or context_strings or plural_strings:
                print(f"  {rust_file}: {len(tr_strings)} tr!, {len(context_strings)} tr_with_context!, {len(plural_strings)} tr_plural!")
            
            all_tr_strings.update(tr_strings)
            all_context_strings.update(context_strings)
            all_plural_strings.update(plural_strings)
            
        except Exception as e:
            print(f"Error reading {rust_file}: {e}")
    
    print(f"\nExtracted strings:")
    print(f"  Regular strings: {len(all_tr_strings)}")
    print(f"  Context strings: {len(all_context_strings)}")
    print(f"  Plural strings: {len(all_plural_strings)}")
    
    # Generate FTL content
    ftl_content = generate_ftl_content(all_tr_strings, all_context_strings, all_plural_strings)
    
    if args.dry_run:
        print(f"\n--- Generated FTL content ---")
        print(ftl_content)
        print(f"--- End of content ---")
    else:
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ftl_content)
        
        print(f"\nGenerated FTL file: {output_path}")
        print(f"Total strings: {len(all_tr_strings) + len(all_context_strings) + len(all_plural_strings)}")

if __name__ == '__main__':
    main() 